version: "3.8"

services:
  composer:
    image: composer:latest
    entrypoint: composer
    command: update
    volumes:
      - .:/app

  phpunit:
    image: jitesoft/phpunit:8.0
    depends_on:
      - composer
    volumes:
      - .:/app
